### ISSUE TITLE
Network activate fails on IndieBlocks error

### ISSUE THREAD

**Issue by janboddez** [janboddez/addon-for-activitypub#21]
```
PHP Fatal error:  Uncaught Error: Call to undefined function IndieBlocks\get_options() in wp-content/plugins/indieblocks/includes/webmention/class-webmention.php:98
Stack trace:
#0 wp-content/plugins/indieblocks/includes/webmention/class-webmention-sender.php(14): IndieBlocks\Webmention\Webmention::get_supported_post_types()
#1 wp-content/plugins/indieblocks/includes/webmention/class-webmention.php(20): IndieBlocks\Webmention\Webmention_Sender::register()
#2 wp-includes/class-wp-hook.php(324): IndieBlocks\Webmention\Webmention::register()
#3 wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 wp-includes/plugin.php(517): WP_Hook->do_action()
```

🤷

**Comment by janboddez** [comment]
I think IndieBlocks uses the Composer autoloader, so something would be calling this (static) class without loading IndieBlocks' functions.php or something.

**Comment by janboddez** [comment]
Still don't understand, but it looks like this might (?) be fixed by removing functions.php from
```
    "autoload": {
        "classmap": ["includes/", "blocks/"],
        "files": ["includes/functions.php"]
    }
```
and instead including it explicitly.

Or move away from
```
add_action( 'init', array( __CLASS__, 'init' ) );
```
in IndieBlocks' Webmention class.

I dunno. Looks like something is triggering autoloading of the Webmention class without the plugin being fully loaded.

**Comment by janboddez** [comment]
Possibly related: https://github.com/humbug/php-scoper/issues/1036

Moving functions.php out of the autoloaded files and requiring it explicitly, for now.
